{{- if .Values.server.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "skill-pool.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skill-pool.server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "skill-pool.server.fullname" . }}
  minReplicas: {{ .Values.server.hpa.minReplicas }}
  maxReplicas: {{ .Values.server.hpa.maxReplicas }}
  metrics:
    {{- if gt (int .Values.server.hpa.targetCPUUtilizationPercentage) 0 }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.server.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if gt (int .Values.server.hpa.targetMemoryUtilizationPercentage) 0 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.server.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end -}}
