#!/usr/bin/env bash
# seed-demo-plugin.sh — publish the demo `rust-axum-toolkit` plugin into the
# `acme` tenant's marketplace.
#
# Why this script exists
# ----------------------
# The E2E acceptance gate (#38) needs a real plugin visible at
#   GET /.claude-plugin/marketplace.json
# so a developer's Claude Code can `/plugin marketplace add` + `/plugin install`
# it. The portal composer at /admin/plugins/new does the same thing through
# the UI, but for repeatable test setup we want a non-interactive shell call
# that hits the same REST endpoint (POST /v1/plugins).
#
# Why this script does NOT use `skill-pool plugin publish`
# --------------------------------------------------------
# See issue #57: the CLI currently serialises a bare `PluginManifest` instead
# of the server's expected `PublishBody` envelope, so the server replies 400.
# This script builds the envelope directly with `curl` + `jq` and will keep
# working after the CLI is fixed.
#
# What it publishes
# -----------------
# A small internal plugin bundling three existing acme skills:
#   - a11y-audit @ 1.0.0
#   - agent-designer @ 1.0.0
#   - agenthub @ 1.0.0
# All three are seeded by `scripts/seed-tenant.sh` so they exist on any
# host that has run the demo seeder.
#
# Idempotency
# -----------
# A second invocation receives HTTP 409 from the server (the unique
# (tenant, slug, version) constraint trips). This script treats 409 as a
# success — the plugin is already published at this version.
#
# Required environment
# --------------------
#   SKILL_POOL_URL    — base URL of the registry. Default: http://127.0.0.1:8080
#   SKILL_POOL_HOST   — Host header to send. Default: acme.localhost
#   SKILL_POOL_TOKEN  — bearer token with skills:publish scope. If unset,
#                       reads ~/.config/skill-pool/config.toml.
#
# Exit codes
# ----------
#   0   published (201) or already exists (409)
#   1   missing dependency or token
#   2   server returned an unexpected non-success / non-409 status

set -euo pipefail

# --- Config --------------------------------------------------------------

SKILL_POOL_URL="${SKILL_POOL_URL:-http://127.0.0.1:8080}"

# The `Host` header we send becomes the origin embedded in marketplace.json's
# `source.url` (see server/src/routes/marketplace.rs::origin_from_request).
# `claude plugin install` clones from that exact URL, so the inbound Host
# MUST be reachable from the developer's machine. When SKILL_POOL_HOST is
# unset we derive it from SKILL_POOL_URL — keeping the port — so the stored
# source URL matches the address the operator actually used to publish.
if [[ -z "${SKILL_POOL_HOST:-}" ]]; then
  # Strip the scheme; whatever's left (host[:port][/path]) becomes the Host.
  derived="${SKILL_POOL_URL#*://}"
  derived="${derived%%/*}"
  if [[ "$derived" == "127.0.0.1"* || "$derived" == "localhost"* ]]; then
    # Substitute the loopback for the tenant subdomain but keep the port.
    port="${derived##*:}"
    if [[ "$port" != "$derived" ]]; then
      SKILL_POOL_HOST="acme.localhost:${port}"
    else
      SKILL_POOL_HOST="acme.localhost"
    fi
  else
    SKILL_POOL_HOST="$derived"
  fi
fi

PLUGIN_SLUG="rust-axum-toolkit"
# Bump on every breaking change to the manifest. The server enforces
# unique (tenant, slug, version) so a re-run with the same version
# returns 409 (treated as idempotent success).
PLUGIN_VERSION="${PLUGIN_VERSION:-1.0.0}"
PLUGIN_NAME="Rust + Axum Toolkit"
PLUGIN_DESCRIPTION="Curated demo plugin bundling accessibility, agent-design, and orchestration skills for the acme tenant."

# --- Dependency check ----------------------------------------------------

for cmd in curl jq; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "error: required command '$cmd' not found on PATH" >&2
    exit 1
  fi
done

# --- Token resolution ----------------------------------------------------

if [[ -z "${SKILL_POOL_TOKEN:-}" ]]; then
  CFG="${HOME}/.config/skill-pool/config.toml"
  if [[ -r "$CFG" ]]; then
    # Pull `token = "..."` out of [registry] without invoking a TOML parser.
    # The file is generated by `scripts/seed-tenant.sh` so its shape is fixed.
    SKILL_POOL_TOKEN=$(awk -F'"' '/^[[:space:]]*token[[:space:]]*=/ {print $2; exit}' "$CFG")
  fi
fi

if [[ -z "${SKILL_POOL_TOKEN:-}" ]]; then
  echo "error: SKILL_POOL_TOKEN not set and ~/.config/skill-pool/config.toml has no token" >&2
  exit 1
fi

# --- Build the PublishBody envelope --------------------------------------
#
# Schema (server/src/routes/plugins.rs::PublishBody):
#   { slug, manifest: { name, version, description, ... }, contents: [...],
#     sourcing_mode: "internal" | "external" | "mirror", status?: "published" }
#
# We use `jq -n` so we never construct JSON by string concatenation; this
# keeps the manifest stable under edits and survives shells that mangle
# quotes (e.g. zsh + history expansion).

BODY=$(jq -n \
  --arg slug "$PLUGIN_SLUG" \
  --arg name "$PLUGIN_NAME" \
  --arg version "$PLUGIN_VERSION" \
  --arg description "$PLUGIN_DESCRIPTION" \
  '{
    slug: $slug,
    manifest: {
      name: $name,
      version: $version,
      description: $description,
      tags: ["rust", "axum", "demo"]
    },
    contents: [
      { kind: "skill", slug: "a11y-audit",     version: "1.0.0" },
      { kind: "skill", slug: "agent-designer", version: "1.0.0" },
      { kind: "skill", slug: "agenthub",       version: "1.0.0" }
    ],
    sourcing_mode: "internal",
    status: "published"
  }')

# --- POST and dispatch on status -----------------------------------------

# Capture body + status in one round-trip by appending the status code to
# stdout with `-w "\n%{http_code}"`. Avoids a second request just to know
# what happened.
RESPONSE=$(curl -sS \
  -H "Host: ${SKILL_POOL_HOST}" \
  -H "Authorization: Bearer ${SKILL_POOL_TOKEN}" \
  -H "Content-Type: application/json" \
  -X POST "${SKILL_POOL_URL}/v1/plugins" \
  --data-binary "$BODY" \
  -w "\n%{http_code}")

# The status is the last line; everything before it is the body.
STATUS=$(printf '%s\n' "$RESPONSE" | tail -n1)
BODY_OUT=$(printf '%s\n' "$RESPONSE" | sed '$d')

case "$STATUS" in
  201)
    echo "OK: published ${PLUGIN_SLUG}@${PLUGIN_VERSION} (HTTP 201)"
    printf '%s\n' "$BODY_OUT" | jq -r '"  plugin_id=\(.slug) sourcing_mode=\(.sourcing_mode) contents=\(.contents | length)"'
    ;;
  409)
    echo "OK: ${PLUGIN_SLUG}@${PLUGIN_VERSION} already published (HTTP 409, idempotent re-run)"
    ;;
  *)
    echo "FAIL: unexpected HTTP ${STATUS} from POST ${SKILL_POOL_URL}/v1/plugins" >&2
    printf '%s\n' "$BODY_OUT" >&2
    exit 2
    ;;
esac

# --- Post-publish marketplace verification -------------------------------
#
# A successful publish should make the plugin visible at
# /.claude-plugin/marketplace.json (modulo the best-effort marketplace
# materialisation in routes/plugins.rs::publish — see comment near
# "Marketplace materialisation hook" in that file). We don't fail the
# script on a missing entry: the publish itself is the gate, and the
# warning gives the operator a clear breadcrumb.

MARKETPLACE=$(curl -sS \
  -H "Host: ${SKILL_POOL_HOST}" \
  "${SKILL_POOL_URL}/.claude-plugin/marketplace.json")

PLUGIN_PRESENT=$(printf '%s' "$MARKETPLACE" | jq --arg slug "$PLUGIN_SLUG" \
  '[.plugins[]? | select(.name == $slug)] | length')

if [[ "$PLUGIN_PRESENT" == "0" ]]; then
  echo "warn: ${PLUGIN_SLUG} not visible in marketplace.json yet (materialisation lag or git error)" >&2
else
  echo "OK: ${PLUGIN_SLUG} visible in marketplace.json (${PLUGIN_PRESENT} entry/entries)"
fi
